src/Entity/Poste.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PosteRepository")
 */
class Poste
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_poste;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Employe", mappedBy="poste")
     */
    private $employes;

    public function __construct()
    {
        $this->employes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPoste(): ?string
    {
        return $this->nom_poste;
    }

    public function setNomPoste(string $nom_poste): self
    {
        $this->nom_poste = $nom_poste;

        return $this;
    }

    /**
     * @return Collection|Employe[]
     */
    public function getEmployes(): Collection
    {
        return $this->employes;
    }

    public function addEmploye(Employe $employe): self
    {
        if (!$this->employes->contains($employe)) {
            $this->employes[] = $employe;
            $employe->setPoste($this);
        }

        return $this;
    }

    public function removeEmploye(Employe $employe): self
    {
        if ($this->employes->contains($employe)) {
            $this->employes->removeElement($employe);
            // set the owning side to null (unless already changed)
            if ($employe->getPoste() === $this) {
                $employe->setPoste(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->nom_poste;
    }
}

src/Controller/PosteController.php
<?php

namespace App\Controller;

use App\Entity\Poste;
use App\Repository\PosteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PosteController extends AbstractController
{
    /**
     * @var PosteRepository
     */
    private $posteRepository;

    public function __construct(PosteRepository $posteRepository)
    {

        $this->posteRepository = $posteRepository;
    }

    /**
     * @Route("/poste", name="poste")
     */
    public function index()
    {
        return $this->render('poste/index.html.twig', [
            'controller_name' => 'PosteController',
        ]);
    }

    /**
     * @param Request $request
     * @return Response
     * @Route("poste/create",name="poste_new",methods={"GET","POST"})
     */
    public function create(Request $request)
    {
        $poste=new Poste();
        $form=$this->createFormBuilder($poste)
            ->add('nom_poste')
            ->getForm();
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($poste);
            $em->flush();
            return $this->redirectToRoute('show_poste');

        }
        return $this->render('poste/create.html.twig',[
            'form'=>$form->createView()
        ]);
    }
    /**
     * @return Response
     * @Route("/show/poste",name="show_poste")
     */
    public function show(){
        $poste=$this->posteRepository->findPoste();
        return $this->render('poste/show.html.twig',[
            'poste'=>$poste
        ]);
    }
    /**
     * @Route("/poste/update/{id}", name="poste_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Poste $poste): Response
    {
        $form=$this->createFormBuilder($poste)
            ->add('nom_poste')
            ->getForm();
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($poste);
            $em->flush();
            return $this->redirectToRoute('show_poste');

        }
        return $this->render('poste/edit.html.twig',[
            'form'=>$form->createView()
        ]);
    }

}

templates/poste/create.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <h2 >INSERER NOUVELLE EMPLOYER</h2>
    {{ form_start(form) }}
    {{ form_row(form.nom_poste) }}

    <input type="submit" value="Enregistrer" class="btn btn-primary btn-lg btn-block">
    {{ form_end(form) }}
{% endblock %}

templates/poste/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <h2 >INSERER NOUVELLE EMPLOYER</h2>
    {{ form_start(form) }}
    {{ form_row(form.nom_poste) }}

    <input type="submit" value="Enregistrer" class="btn btn-primary btn-lg btn-block">
    {{ form_end(form) }}
{% endblock %}

templates/poste/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PosteController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/projet_NL/ENT_NL/ENT/src/Controller/PosteController.php'|file_link(0) }}">src/Controller/PosteController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/projet_NL/ENT_NL/ENT/templates/poste/index.html.twig'|file_link(0) }}">templates/poste/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/poste/show.html.twig
{% extends 'base.html.twig' %}
{% block body %}


    <h3 class="text-success" align="center">Liste des Poste</h3>
    <a type="submit" href="{{ path('poste_new') }}" class="btn btn-success">Nouveau</a>
    <table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">Nom</th>
        <th scope="col">Action</th>
    </tr>
    {% for p in poste %}
    </thead>
    <tbody>
    <tr class="table-active">
        <td >{{ p.nomPoste }}</td>
        <td> <a type="submit" href="{{ path('poste_edit',{id:p.id}) }}" class="btn btn-success">Modifier</a>
    </tr>
    {% endfor %}
{% endblock %}