src/Entity/Departement.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DepartementRepository")
 */
class Departement
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_dep;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Employe", mappedBy="departement")
     */
    private $employes;

    public function __construct()
    {
        $this->employes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomDep(): ?string
    {
        return $this->nom_dep;
    }

    public function setNomDep(string $nom_dep): self
    {
        $this->nom_dep = $nom_dep;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Employe[]
     */
    public function getEmployes(): Collection
    {
        return $this->employes;
    }

    public function addEmploye(Employe $employe): self
    {
        if (!$this->employes->contains($employe)) {
            $this->employes[] = $employe;
            $employe->setDepartement($this);
        }

        return $this;
    }

    public function removeEmploye(Employe $employe): self
    {
        if ($this->employes->contains($employe)) {
            $this->employes->removeElement($employe);
            // set the owning side to null (unless already changed)
            if ($employe->getDepartement() === $this) {
                $employe->setDepartement(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->nom_dep;
    }
}

src/Controller/DepartementController.php
<?php

namespace App\Controller;

use App\Entity\Departement;
use App\Repository\DepartementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DepartementController extends AbstractController
{
    /**
     * @var DepartementRepository
     */
    private $departementRepositiry;

    public function __construct(DepartementRepository $departementRepositiry)
    {

        $this->departementRepositiry = $departementRepositiry;
    }

    /**
     * @Route("/departement", name="departement")
     */
    public function index()
    {
        return $this->render('departement/index.html.twig', [
            'controller_name' => 'DepartementController',
        ]);
    }

    /**
     * @param Request $request
     * @return Response
     * @Route("/departement/nouveau",name="departement_new",methods={"GET","POST"})
     */
    public function create(Request $request)
    {
        $departement=new Departement();
        $form=$this->createFormBuilder($departement)
            ->add('nom_dep')
            ->add('description')
            ->getForm();
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($departement);
            $em->flush();
            return $this->redirectToRoute('liste_departement');
            
        }
        return $this->render('departement/nouveau.html.twig',[
            'form'=>$form->createView()
        ]);

    }

    /**
     * @return Response
     * @Route("/liste/departement",name="liste_departement")
     */
    public function liste(){
        $departement=$this->departementRepositiry->findDepartement();
        return $this->render('departement/liste.html.twig',[
            'departement'=>$departement
        ]);
    }
    /**
     * @Route("/departement/update/{id}", name="departement_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Departement $departement): Response
    {

        $form=$this->createFormBuilder($departement)
            ->add('nom_dep')
            ->add('description')
            ->getForm();
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($departement);
            $em->flush();
            return $this->redirectToRoute('liste_departement');

        }
        return $this->render('departement/update.html.twig',[
            'form'=>$form->createView()
        ]);
    }

    /**
     * @param Departement $departement
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Route("/liste/departement/{id}",name="departement_delete")
     */
    public function delete(Departement $departement){
            if (isset($departement)){
                $em=$this->getDoctrine()->getManager();
                $em->remove($departement);
                $em->flush();
                return $this->redirectToRoute('liste_departement');
            }

    }
 }

templates/departement/delete.html.twig
<form method="post" action="{{ path('departement_delete', {'id': departement.id }) }}" onsubmit="return confirm('voulez-vous vraiment supprimer?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ departement.id) }}">
    <button class="btn btn-danger btn-lg btn-block">Supprimer</button>
</form>

templates/departement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DepartementController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/projet_NL/ENT_NL/ENT/src/Controller/DepartementController.php'|file_link(0) }}">src/Controller/DepartementController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/projet_NL/ENT_NL/ENT/templates/departement/index.html.twig'|file_link(0) }}">templates/departement/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/departement/liste.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <h3 class="text-success" align="center">Liste des Departement</h3>
    <a type="submit" href="{{ path('departement_new') }}" class="btn btn-success">Nouveau</a>
    <table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">Nom</th>
        <th scope="col">Action</th>
    </tr>
    {% for d in departement %}
    </thead>
    <tbody>
    <tr class="table-active">
        <td >{{ d.nomDep }}</td>
        <td> <a type="submit" href="{{ path('departement_edit',{id:d.id}) }}" class="btn btn-success">Modifier</a>
    </tr>
    {% endfor %}
{% endblock %}

templates/departement/nouveau.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <h2 >INSERER NOUVELLE DEPARTEMENT</h2>
    {{ form_start(form) }}
    {{ form_row(form.nom_dep) }}
    {{ form_row(form.description) }}
    <input type="submit" value="Inserer" class="btn btn-primary btn-lg btn-block">
    {{ form_end(form) }}
{% endblock %}

templates/departement/update.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <h2 >MODIFIER LE DEPARTEMENT</h2>
    {{ form_start(form) }}
    {{ form_row(form.nom_dep) }}
    {{ form_row(form.description) }}
    <input type="submit" value="Enregistrer" class="btn btn-primary btn-lg btn-block">
    {{ form_end(form) }}
{% endblock %}