src/Entity/Employe.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EmployeRepository")
 */
class Employe
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Poste", inversedBy="employes")
     */
    private $poste;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Departement", inversedBy="employes")
     */
    private $departement;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $num_matricule;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="id_envoye")
     */
    private $id_recepeteur;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="id_recepteur")
     */
    private $messages;

    public function __construct()
    {
        $this->id_recepeteur = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPoste(): ?Poste
    {
        return $this->poste;
    }

    public function setPoste(?Poste $poste): self
    {
        $this->poste = $poste;

        return $this;
    }

    public function getDepartement(): ?Departement
    {
        return $this->departement;
    }

    public function setDepartement(?Departement $departement): self
    {
        $this->departement = $departement;

        return $this;
    }

    public function getNumMatricule(): ?string
    {
        return $this->num_matricule;
    }

    public function setNumMatricule(?string $num_matricule): self
    {
        $this->num_matricule = $num_matricule;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getIdRecepeteur(): Collection
    {
        return $this->id_recepeteur;
    }

    public function addIdRecepeteur(Message $idRecepeteur): self
    {
        if (!$this->id_recepeteur->contains($idRecepeteur)) {
            $this->id_recepeteur[] = $idRecepeteur;
            $idRecepeteur->setIdEnvoye($this);
        }

        return $this;
    }

    public function removeIdRecepeteur(Message $idRecepeteur): self
    {
        if ($this->id_recepeteur->contains($idRecepeteur)) {
            $this->id_recepeteur->removeElement($idRecepeteur);
            // set the owning side to null (unless already changed)
            if ($idRecepeteur->getIdEnvoye() === $this) {
                $idRecepeteur->setIdEnvoye(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setIdRecepteur($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getIdRecepteur() === $this) {
                $message->setIdRecepteur(null);
            }
        }

        return $this;
    }
}

src/Controller/EmployeController.php
<?php

namespace App\Controller;

use App\Entity\Departement;
use App\Entity\Employe;
use App\Entity\Poste;
use App\Repository\EmployeRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\FrameworkBundle\Tests\Fixtures\Validation\Category;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class EmployeController extends AbstractController
{
    /**
     * @var EmployeRepository
     */
    private $employeRepository;
    /**
     * @var SessionInterface
     */
    private $session;

    public function __construct(EmployeRepository $employeRepository, SessionInterface $session)
    {

        $this->employeRepository = $employeRepository;
        $this->session = $session;
    }

    /**
     * @Route("/employe", name="employe")
     */
    public function index()
    {
        return $this->render('employe/index.html.twig', [
            'controller_name' => 'EmployeController',
        ]);
    }
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/employe/new", name="nouveau_employe")
     */
    public function nouveau(){
        return $this->render('employe/new.html.twig');
    }
    /**
     * @param Request $request
     * @return Response
     * @throws \Exception
     * @Route("/new/employe", name="new_employe")
     */
    public  function create(Request $request){

        $employe=new Employe();
        $form=$this->createFormBuilder($employe)
        ->add('departement',EntityType::class,[
            'class'=>Departement::class,
            'query_builder'=>function(EntityRepository $entityRepository){
            return $entityRepository->createQueryBuilder('d')->orderBy('d.nom_dep','ASC');

            }

        ])
        ->add('poste',EntityType::class,[
                'class'=>Poste::class,
                'query_builder'=>function(EntityRepository $entityRepository){
                    return $entityRepository->createQueryBuilder('p')->orderBy('p.nom_poste','ASC');

                }

            ])
        ->add('nom')
        ->add('num_matricule')
        ->add('username')
        ->add('password')
        ->getForm();
    $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $pass=sha1($employe->getPassword());
            $employe->setPassword($pass);
            $em=$this->getDoctrine()->getManager();
            $em->persist($employe);
            $em->flush();
            return $this->redirectToRoute('read_employe');
        }
        return $this->render('employe/new.html.twig',[
            'form'=>$form->createView()
        ]);
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     * @Route("/login/employe", name="login_employe")
     */
    public function loginEmploye(Request $request)
    {
        $formLogin=$this->createFormBuilder()
            ->add('username',TextType::class,[
                'label'=>' ',
                'attr'=>[
                    'placeholder'=>'Utilisateur'
                ]
            ])
            ->add('password',PasswordType::class,[
                'label'=>' ',
                'attr'=>[
                    'placeholder'=>'Mot de passe'
                ]
            ])
            ->getForm();

        $formLogin->handleRequest($request);

        if($formLogin->isSubmitted() && $formLogin->isValid())
        {
            $username=$request->request->get("form")['username'];
            $password=$request->request->get("form")['password'];
            $dirigean=$this->employeRepository->findemp($username,$password);
            if(count($dirigean)===1){
                $session=$this->session;
                $session->set('username_employe',$username);
                $sessUsername=$session->get('username');
                    return $this->redirectToRoute('employe_accueil');
            }else{
                $erro="Username ou mot de passe incorrect";
                return $this->render('employe/login.html.twig', [
                    'form'=>$formLogin->createView(),
                    'err'=>$erro
                ]);
            }

        }

        return $this->render('employe/login.html.twig', [
            'form'=>$formLogin->createView()
        ]);
    }
    /**
     * @Route("/lougout/employe", name="logoutemploue")
     */
    public function logout(){
        $this->session->clear();
        return $this->redirectToRoute('user');
    }

    /**
     * @return Response
     * @Route("/read/employe",name="read_employe")
     */
    public  function read(){
     $employe=$this->employeRepository->findEmploye();
     return $this->render('employe/read.html.twig',[
         'employe'=>$employe
     ]);
    }
    /**
     * @Route("/employe/update/{id}", name="employe_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Employe $employe): Response
    {

        $form=$this->createFormBuilder($employe)
            ->add('departement',EntityType::class,[
                'class'=>Departement::class,
                'query_builder'=>function(EntityRepository $entityRepository){
                    return $entityRepository->createQueryBuilder('d')->orderBy('d.nom_dep','ASC');

                }

            ])
            ->add('poste',EntityType::class,[
                'class'=>Poste::class,
                'query_builder'=>function(EntityRepository $entityRepository){
                    return $entityRepository->createQueryBuilder('p')->orderBy('p.nom_poste','ASC');

                }

            ])
            ->add('nom')
            ->add('num_matricule')
            ->add('username')
            ->add('password')
            ->getForm();
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $em=$this->getDoctrine()->getManager();
            $em->persist($employe);
            $em->flush();
            return $this->redirectToRoute('read_employe');
        }
        return $this->render('employe/edit.html.twig',[
            'form'=>$form->createView()
        ]);
    }

    /**
     * @param Employe $employe
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Route("/read/employe/{id}",name="employe_delete")
     */
    public function delete(Employe $employe){
        if (isset($employe)){
            $em=$this->getDoctrine()->getManager();
            $em->remove($employe);
            $em->flush();
            return $this->redirectToRoute('read_employe');
        }

    }

    /**
     * @param Employe $employe
     * @return Response
     * @Route("voir/employe/{id}",name="employe_voir")
     */
    public function voir(Employe $employe){
        return $this->render('employe/voir.html.twig',[
            'e'=>$employe
        ]);

    }

     /**
     * @param Request $request
     * @return Response
     * @Route("/acceuil/employe",name="employe_accueil")
     */
    public function accueil(Request $request)
    {
        return $this->render('employe/accueil.html.twig');
    }

    /**
    * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     * @Route("message/employe/{id}",name="envoye_message")
     */
   public function message(Request $request){

   }
}

templates/employe/Form_message.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <h2 >INSERER NOUVELLE EMPLOYER</h2>
    {{ form_start(form) }}
    {{ form_row(form.contenu) }}
    <input type="submit" value="Envoyer" class="btn btn-primary btn-lg btn-block">
    {{ form_end(form) }}
{% endblock %}

templates/employe/accueil.html.twig
{% extends 'base.html.twig' %}
{% block body %}

{% endblock %}

templates/employe/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <h2 >MODIFIER L'EMPLOYER</h2>
    {{ form_start(form) }}
    {{ form_row(form.nom) }}
    {{ form_row(form.departement) }}
    {{ form_row(form.poste) }}
    {{ form_row(form.num_matricule) }}
    {{ form_row(form.username) }}
    {{ form_row(form.password) }}
    <input type="submit" value="Enregistrer" class="btn btn-primary btn-lg btn-block">
    {{ form_end(form) }}
{% endblock %}

templates/employe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EmployeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/projet_NL/ENT_NL/ENT/src/Controller/EmployeController.php'|file_link(0) }}">src/Controller/EmployeController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/projet_NL/ENT_NL/ENT/templates/employe/index.html.twig'|file_link(0) }}">templates/employe/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/employe/login.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<style>
    body{
        margin: 0;
        padding: 0;
        font-family: sans-serif;
        background: #ccc;
    }
    section{
        width: 100%;
        height: 100vh;
        background-image: url("/public/images/bg1.jpg");
        background-size: cover;
        margin-top: -40px;
        padding: 0;
    }
    .box{
        width: 300px;
        padding: 40px;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);

        text-align: center;
    }
    .box h1{
        color: #3b91b2;
        text-transform: uppercase;
        font-weight: 500;
    }
    .box input[type="text"],.box input[type="password"]{
        border:0;
        background: none;
        display: block;
        margin: 20px auto;
        text-align: center;
        border: 2px solid #FFFFFF;
        padding: 14px 10px;
        width: 200px;
        outline: none;
        color: white;
        border-radius:24px ;
        transition: 0.25s;
    }
    .box input[type="text"]:focus,.box input[type="password"]:focus{
        width: 280px;
        border-color: #3b91b2;
    }
    .box input[type="submit"]{
        border:0;
        background: #3b91b2;
        display: block;
        margin: 20px auto;
        text-align: center;
        border: 2px solid #3b91b2;
        padding: 14px 40px;
        width: 150px;
        outline: none;
        color: white;
        border-radius:24px ;
        transition: 0.25s;
        cursor: pointer;
    }
    .box input[type="submit"]:hover{
        background: none;
    }
</style>
<body>
    {% if err is defined %}
        {{ err }}
    {% else %}
        <p></p>
    {% endif %}
    <section>
    <div class="box">
        {{ form_start(form) }}
        <h1>Login Employé</h1>
        {{ form_row(form.username) }}
        {{ form_row(form.password) }}
        <input type="submit" value="Se connecter" class="btn">
        {{ form_end(form) }}
    </div>
    </section>




</body>
</html>

templates/employe/new.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <h2 >INSERER NOUVELLE EMPLOYER</h2>
    {{ form_start(form) }}
    {{ form_row(form.nom) }}
    {{ form_row(form.departement) }}
    {{ form_row(form.poste) }}
    {{ form_row(form.num_matricule) }}
    {{ form_row(form.username) }}
    {{ form_row(form.password) }}
    <input type="submit" value="Inserer" class="btn btn-primary btn-lg btn-block">
    {{ form_end(form) }}
{% endblock %}

templates/employe/read.html.twig
{% extends 'base.html.twig' %}
{% block body %}


      <h3 class="text-success" align="center">Liste des Employées</h3>
      <a type="submit" href="{{ path('new_employe') }}" class="btn btn-success">Nouveau</a>
      <table class="table table-hover">
        <thead>
          <tr>
             <th scope="col">Nom</th>
             <th scope="col">Poste</th>
             <th scope="col">Departement</th>
             <th scope="col">N° Matricule</th>
             <th scope="col">Action</th>
         </tr>
      {% for e in employe %}
       </thead>
       <tbody>
           <tr class="table-active">
               <td >{{ e.nom }}</td>
               <td>{{ e.poste }}</td>
               <td>{{ e.departement }}</td>
               <td>{{ e.numMatricule }}</td>
               <td><a type="submit"  href="{{ path('employe_voir',{id:e.id}) }}" class="btn btn-info">Voir</a>
                   <a type="submit" href="{{ path('employe_edit',{id:e.id}) }}" class="btn btn-success">Modifier</a>
                   <a type="submit" href="{{ path('employe_delete',{id:e.id}) }}" class="btn btn-danger">Supprimer</a>
               </td>
           </tr>
        </tbody>
      </table>
    {% endfor %}
    

    
{% endblock %}

templates/employe/voir.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="container">
        <br>
        <div class="ol-sm-3">

        </div>
        <center>
            <div class="col-sm-6" align="left" style="background-color: #C0C0C0; padding: 25px 20px 20px 30px">

                <div class="rec">

                    <b><p class="text-primary" align="center"><strong>Coordonnée de {{ e.nom }}</strong></p></b>
                    <hr>
                    <b>Poste:</b><br>
                    {{ e.poste }}<br>
                    <hr>
                    <b>Departement:</b><br>
                    {{ e.departement }}<br>

                    <hr>
                    <b>N° Matricule:</b><br>
                    {{ e.numMatricule }}<br>
                    <hr>

                </div>
                <br>
                <br>
                <div>
                    <a href="{{ path('read_employe') }}" class="btn btn-info">OK</a><br>
                </div>
            </div>
        </center>

        <div class="col-sm-3">

        </div>
    </div>




{% endblock %}